/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'yangsai' at '16-10-21 下午9:30' with Gradle 2.8
 *
 * @author yangsai, @date 16-10-21 下午9:30
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
