/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'yangsai' at '16-10-21 下午9:30' with Gradle 2.8
 *
 * @author yangsai, @date 16-10-21 下午9:30
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
